#!/bin/bash

if [[ "$1" == *".jpg" ]]; then
	feh "$1"
	exit
fi

if [[ "$1" == "https://chaturbate.com/"*"/" ]]; then
	mpv --volume=0 "$(curl -s -N $1 | grep -m1 -o https://.*m3u8 | sed 's/\\u002D/-/g')"
	exit
fi

if [[ "$1" == "https://www.xnxx.com/video"* ]]; then
	mpv --volume=0 "$1"
	exit
fi

if [[ "$1" == "https://www.xvideos.com/video"* ]]; then
	mpv --volume=0 "$1"
	exit
fi

if [[ "$1" == "https://www.reddit.com/"* ]]; then
	firefox "$1"
	exit
fi

mpv "$1"
