#!/bin/bash

cb=$(xsel -ob)

if [[ "$cb" == *".jpg" ]]; then
	feh "$1"
	exit
fi

if [[ "$cb" == "https://chaturbate.com/"*"/" ]]; then
	mpv --volume=0 "$(curl -s -N $cb | grep -m1 -o https://.*m3u8 | sed 's/\\u002D/-/g')"
	exit
fi

if [[ "$cb" == "https://www.xnxx.com/video"* ]]; then
	mpv --volume=0 "$cb"
	exit
fi

if [[ "$cb" == "https://www.xvideos.com/video"* ]]; then
	mpv --volume=0 "$cb"
	exit
fi

if [[ "$cb" == "https://www.reddit.com/"* ]]; then
	firefox "$cb"
	exit
fi

mpv "$cb"
