#!/bin/bash

if [[ "$(xsel -ob)" == *".jpg" ]]; then
	feh "$(xsel -ob)"
	exit
fi

if [[ "$(xsel -ob)" == "https://chaturbate.com/"*"/" ]]; then
	mpv --volume=0 "$(curl -s -N $(xsel -ob) | grep -m1 -o https://.*m3u8 | sed 's/\\u002D/-/g')"
	exit
fi

if [[ "$(xsel -ob)" == "https://www.xnxx.com/video"* ]]; then
	mpv --volume=0 "$(xsel -ob)"
	exit
fi

if [[ "$(xsel -ob)" == "https://www.xvideos.com/video"* ]]; then
	mpv --volume=0 "$(xsel -ob)"
	exit
fi

if [[ "$(xsel -ob)" == "https://www.reddit.com/"* ]]; then
	firefox "$(xsel -ob)"
	exit
fi

mpv "$(xsel -ob)"
