#!/bin/bash

while true
do
	echo -ne "\nEnter hostname: " && read hname
	echo -ne "Confirm hostname: " && read hname2
	[[ "$hname" != "$hname2" ]] || break
done

while true
do
	echo -ne "\nEnter username: " && read usrname
	echo -ne "Confirm username: " && read usrname2
	[[ "$usrname" != "$usrname2" ]] || break
done

echo " "
sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
sed -i 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers

useradd -m $usrname
usermod -aG wheel,storage,video,audio,optical $usrname
while ! passwd $usrname; do echo " "; done
passwd -l root

sed -i 's/^#Color/Color/g' /etc/pacman.conf
awk -i inplace '/#\[multilib\]/ { print substr($0,2); getline; print substr($0,2); next }; !/#\[multilib\]/ { print $0 }' /etc/pacman.conf

if ! grep -F pwfeedback /etc/sudoers; then
	awk -i inplace '/^# Defaults!REBOOT !log_output/ { print $0"\n\nDefaults pwfeedback" }; !/^# Defaults!REBOOT !log_output/ { print $0 }' /etc/sudoers
fi

echo LANG=en_US.UTF-8 > /etc/locale.conf
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
ln -sf /usr/share/zoneinfo/$(curl -s ipinfo.io | sed 's/[{},"]//g' | grep timezone | cut -d: -f 2 | sed 's/^ //g') /etc/localtime
locale-gen
hwclock -w

echo $hname > /etc/hostname
echo "# Static table lookup for hostnames." > /etc/hosts
echo "# See hosts(5) for details." >> /etc/hosts
echo >> /etc/hosts
echo "127.0.0.1	localhost" >> /etc/hosts
echo "::1		localhost" >> /etc/hosts
echo "127.0.1.1	$hname.localdomain	$hname" >> /etc/hosts

pacman -Syyu arch-install-scripts --noconfirm

echo "# Static information about the filesystems." > /etc/fstab
echo "# See fstab(5) for details." >> /etc/fstab
echo >> /etc/fstab
echo "# <file system> <dir> <type> <options> <dump> <pass>" >> /etc/fstab
echo >> /etc/fstab
genfstab -U / >> /etc/fstab

pacman -Rns arch-install-scripts --noconfirm

echo " "
echo "********************************"
echo "     creating swap file.....    "
echo "********************************"
dd if=/dev/zero of=/swapfile bs=1M count=2048 status=progress
chmod 600 /swapfile
mkswap /swapfile
echo "/swapfile none swap sw 0 0" >> /etc/fstab
echo " "

curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/bin/youtube-dl
chmod a+rx /usr/bin/youtube-dl

if ! nvim --version > /dev/null; then pacman -S neovim  --noconfirm; fi
pacman -S $(cat pkglist | tr '\n' ' ') --noconfirm

systemctl enable sshd
systemctl enable NetworkManager
ln -sf /usr/bin/nvim /usr/bin/vim
ln -sf /usr/bin/nvim /usr/bin/vi

mv lightdm-mini-greeter.conf /etc/lightdm
mv slick-greeter.conf /etc/lightdm

sed -i 's/^#user-session=default/user-session=default/g' /etc/lightdm/lightdm.conf
sed -i "s/dman79/$usrname/g" /etc/lightdm/lightdm-mini-greeter.conf

git clone https://github.com/kungfubeaner/my-st-terminal-setup
cd my-st-terminal-setup
sudo -u $usrname make
sudo make install
cd ..
rm -rf my-st-terminal-setup

dirname=$(pwd)
cd /home/$usrname
sudo -u $usrname git clone https://aur.archlinux.org/yay
cd /home/$usrname/yay
sudo -u $usrname makepkg -sri --noconfirm
cd ..
rm -rf yay

cd $dirname
sudo -u $usrname yay -S $(cat aurlist | tr '\n' ' ') --removemake --answerclean None --answerdiff None --answeredit None --noconfirm
sudo -u $usrname yay -Sc --noconfirm
sed -i 's/%wheel ALL=(ALL) NOPASSWD: ALL/# %wheel ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers

ln -sf /usr/bin/neroAacTag /usr/bin/neroaactag
ln -sf /usr/bin/neroAacEnc /usr/bin/neroaacenc
ln -sf /usr/bin/neroAacDec /usr/bin/neroaacdec

cd theming
unzip Black-Frost-Suru_1.6.2.zip
mv Black-Frost-Suru /usr/share/icons

cd .icons
mv * /usr/share/icons
cd ..

cd .themes
mv * /usr/share/themes
cd ..

cd .wallpapers
mkdir /usr/share/backgrounds
mv * /usr/share/backgrounds

cd $dirname
sudo -u $usrname mkdir /home/$usrname/ff-addon-settings
mv *.json /home/$usrname/ff-addon-settings
mv *.txt /home/$usrname/ff-addon-settings
chown $usrname:$usrname /home/$usrname/ff-addon-settings/*.json
chown $usrname:$username /home/$usrname/ff-addon-settings/*.txt

sudo -u $usrname cp -r dotfiles/.config/* /home/$usrname/.config
sudo -u $usrname mkdir /home/$usrname/scripts
sudo -u $usrname cp -r dotfiles/scripts/* /home/$usrname/scripts
sudo -u $usrname mkdir /home/$usrname/.config/gtk-3.0
sudo -u $usrname cp -r dotfiles/gtk-3.0/* /home/$usrname/.config/gtk-3.0
rm -rf dotfiles/.config
sed -i "s/dman79/$usrname/g" dotfiles/.gtkrc-2.0
sudo -u $usrname cp -r dotfiles/.???* /home/$usrname/
sudo -u $usrname ln -s /home/$usrname/.vim /home/$usrname/.config/nvim
sudo -u $usrname ln -s /home/$usrname/.vimrc /home/$usrname/.vim/init.vim

systemctl enable lightdm
sed -i 's/^#greeter-session=example-gtk-gnome/greeter-session=lightdm-mini-greeter/g' /etc/lightdm/lightdm.conf

#sed -i 's/bspwm/mate/g' /home/$usrname/.dmrc
pip list --outdated | awk 'NR>2 { print $1 }' | xargs -l1 pip install --upgrade

echo " "
echo "*************************** "
echo " umount -R /mnt             "
echo " remove installation media  "
echo " reboot                     "
echo "*************************** "

cd; rm -rf arch-config
