#!/bin/bash

while true
do
	echo -ne "\nEnter hostname: " && read hname
	echo -ne "Confirm hostname: " && read hname2
	[[ "$hname" != "$hname2" ]] || break
done

while true
do
	echo -ne "\nEnter username: " && read usrname
	echo -ne "Confirm username: " && read usrname2
	[[ "$usrname" != "$usrname2" ]] || break
done

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers

useradd -m $usrname
usermod -aG wheel,storage,video,audio,optical $usrname
passwd $usrname
passwd -l root

sed -i 's/^#Color/Color/g' /etc/pacman.conf
awk -i inplace '/#\[multilib\]/ { print substr($0,2); getline; print substr($0,2); next }; !/#\[multilib\]/ { print $0 }' /etc/pacman.conf

echo LANG=en_US.UTF-8 > /etc/locale.conf
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
ln -sf /usr/share/zoneinfo/$(curl -s ipinfo.io | sed 's/[{},"]//g' | grep timezone | cut -d: -f 2 | sed 's/^ //g') /etc/localtime
locale-gen
hwclock -w

echo $hname > /etc/hostname
echo "# Static table lookup for hostnames." > /etc/hosts
echo "# See hosts(5) for details." >> /etc/hosts
echo >> /etc/hosts
echo "127.0.0.1	localhost" >> /etc/hosts
echo "::1		localhost" >> /etc/hosts
echo "127.0.1.1	$hname.localdomain	$hname" >> /etc/hosts

pacman -Syyu arch-install-scripts

echo "# Static information about the filesystems." > /etc/fstab
echo "# See fstab(5) for details." >> /etc/fstab
echo >> /etc/fstab
echo "# <file system> <dir> <type> <options> <dump> <pass>" >> /etc/fstab
echo >> /etc/fstab
genfstab -U / >> /etc/fstab

echo " "
echo "********************************"
echo "     creating swap file.....    "
echo "********************************"
dd if=/dev/zero of=/swapfile bs=1M count=2048 status=progress
chmod 600 /swapfile
mkswap /swapfile
echo "/swapfile none swap sw 0 0" >> /etc/fstab
echo " "

pacman -Rns arch-install-scripts

curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/bin/youtube-dl
chmod a+rx /usr/bin/youtube-dl

pacman -S $(cat pkglist)

ln -sf /usr/bin/nvim /usr/bin/vim
ln -sf /usr/bin/nvim /usr/bin/vi

mv lightdm-mini-greeter.conf /etc/lightdm
mv slick-greeter.conf /etc/lightdm

sed -i 's/^#greeter-session=example-gtk-gnome/greeter-session=lightdm-slick-greeter/g' /etc/lightdm/lightdm.conf
sed -i 's/^#user-session=default/user-session=default/g' /etc/lightdm/lightdm.conf
sed -i "s/dman79/$usrname/g" /etc/lightdm/lightdm-mini-greeter.conf

cd theming
unzip Black-Frost-Suru_1.6.2.zip
cd ..

cd theming
mv Black-Frost-Suru /usr/share/icons

cd .icons
mv * /usr/share/icons
cd ..

cd .themes
mv * /usr/share/themes
cd ..

cd .wallpapers
mkdir /usr/share/backgrounds
mv * /usr/share/backgrounds
