#! /bin/sh

killall -q sxhkd &
killall -q compton &
killall -q polybar &
sleep 0.3

sxhkd &
compton &
xsetroot -cursor_name left_ptr &
feh --bg-fill /usr/share/backgrounds/frost-moon.jpg &

#while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done &
polybar example &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config normal_border_color	"#004204"
bspc config normal_border_color		"#113711"
bspc config focused_border_color	"#008A09"

#bspc config normal_border_color		"#8A3D70"
#bspc config focused_border_color	"#FF66CC"

bspc config automatic_scheme alternate
bspc config left_padding 0
bspc config right_padding 0
bspc config top_padding 0
bspc config bottom_padding 2

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox border=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop state=floating
bspc rule -a mpv state=floating border=off
